name: CI

on:
  push:
    branches: ["main", "ci-cd"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./patient-management
        run: npm install

      - name: Run Jest tests
        working-directory: ./patient-management
        run: npm run test -- --verbose

      - name: Run linting
        working-directory: ./patient-management
        run: npm run lint

      - name: Run Cypress tests
        working-directory: ./patient-management
        run: npx start-server-and-test 'npm run dev' http://localhost:5173 'npx cypress run'

      - name: Build production bundle
        working-directory: ./patient-management
        run: npm run build

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        working-directory: ./patient-management
        run: flyctl deploy --config fly.toml --verbose
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
